#pragma once

#include "AST_Data.hpp"
#include "AST_Base.hpp"
#include "AST_Declaration.hpp"
#include "AST_Declaration_COP.hpp"
#include "AST_Declaration_Local.hpp"
#include "AST_Evaluator.hpp"
#include "AST_Generic.hpp"
#include "AST_Literal.hpp"
#include "AST_Memory.hpp"
#include "AST_Operation.hpp"
#include "AST_Expression.hpp"
#include "AST_Statement.hpp"
#include "AST_Type.hpp"