
# main velox toolchain config
# it's the default configuration
# set config field to specify a sub configuration to compile (use his name in sub_configs)

# all fields will be stored as define element also


# ======================
# velox-compiler section 
# ======================

[target]
project_name        = "velox_debug.toml"        # if empty, the workspace file name will be used
arch                = "x86_64"                # x86_64, aarch64, wasm32, ...
os                  = "linux-gnu"                  # linux, windows, macos, ...
vendor              = "pc"              # apple, pc, ...
abi                 = "gnu"                 # gnu, msvc, ...
abi_size            = "LP64"            # LP64, ILP32, LLP64
libc                = ""                # musl, glibc, bionic, msvc, ...
cpu                 = ""                 # overrides host cpu detection
features            = ""            # ex: "+avx2,+bmi2"
code_model          = "small"          # tiny, small, kernel, medium, large
reloc_model         = "pic"         # PIC, Static, DynamicNoPIC, ropi, rwpi, ropi_rwpi
sub_config          = ""          # sub .toml name to apply after this .toml 
emits               = [                             # bin, llvm, obj, asm, bc, s_lib, d_lib
  "bin", "llvm", "obj", "asm", "bc", "s_lib", "d_lib", 
]                

[profile]
# the debug profile will override some options
debug               = false                # true = disable optimization, enable debug info
optimization        = "O0"       # O0,O1,O2,O3,Os,Oz

[log]
# all, filesystem, lexer, preprocessor, parser, binder, exporter, 
# resolver_symbol, resolver_type, resolver_semantic, 
# codegen, optimization, emit, linker
logs = [
  
]                                    

[warning]
# all, extra, pedantic, unused, dead_code, as_error
warnings = [
  
]
# 1, 2, 3
level               = 0  


[debug]
# ast
debugs = [
  
]

[define]


[undefine]
undefines = [
  
]

[directory]
project             = "./"
build               = "./build"  
source              = "./src"  
vendor              = "./vendor"  
ffi_json            = "./binding/ffi_json"  
binding             = "./binding"  
compiler            = "/home/flo/bin/velox-compiler"  
stdlib              = "/home/flo/.local/share/velox/lib/std"  
packages            = "/home/flo/.local/share/velox/lib/packages"

[config]
# designed to target a sub configuration parameters


# ============
# LLVM section
# ============
# This configuration is strictly for LLVM passes and code generation.
# It does not affect your Velox preprocessor.

[llvm]
triple              = ""          # override triple, else auto-generated from target
verify_module       = true     # verify before AND after passes
args = [                                      # custom raw flags passed to LLVM
  
]
