#pragma once

#include "ast_base.hpp"
#include "ast_data.hpp"
#include "ast_declaration.hpp"
#include "ast_declaration_cop.hpp"
#include "ast_declaration_local.hpp"
#include "ast_evaluator.hpp"
#include "ast_expression.hpp"
#include "ast_generic.hpp"
#include "ast_literal.hpp"
#include "ast_memory.hpp"
#include "ast_operation.hpp"
#include "ast_statement.hpp"
#include "ast_type.hpp"